### PR TITLE
Convert demo to using new Speech JS SDK

### PR DESCRIPTION
**Pull request by nfriedly**
@daniel-bolanos please test and code review. 

I'm still considering some significant API changes to the [SDK](https://github.com/watson-developer-cloud/speech-javascript-sdk), so I understand if you want to wait until it's more settled before merging, but I mostly wanted to get you to take a look at what I have so far. I should probably also get a code review for the SDK...

### CODE REVIEW

**Comment by daniel-bolanos** [comment]
Hello Nathan, this looks very good, it makes the code simpler and cleaner. Easier to read.
I would like to test this running against prod, do you have it pushed somewhere?

**Comment by germanattanasio** [comment]
@daniel-bolanos: https://github.com/watson-developer-cloud/speech-javascript-sdk

**Comment by nfriedly** [comment]
I just pushed a copy of this to https://speech-js-sdk-demo.mybluemix.net/ - although mic input seems to be failing me in firefox now (the local copy still works, and they both work in chrome.) I'll do a bit of investigation and report back.

Although I just realized that I still need to connect the opt-out param.

**Comment by nfriedly** [comment]
Op, I figured it out. The `node_modules/` folder is in `.cfignore` as I eas expecting, but it doesn't ignore or rebuild the JS during a `cf push`, and it happened to grab a bundle from a point in time where one of my experiments in the speech-js-sdk had broken things. (I'm trying to send it through a MediaRecorder to get opus audio without having to do the compression in JS.)

Anyways, it's fixed now. We might want to look into rebuilding the browserfy bundle automatically on bluemix though. A simple option might be to put in a `scripts.postinstall` in package.json to do it.

**Comment by daniel-bolanos** [comment]
Hi @nfriedly , I just tested it. It seems to work in chrom for mic capture, but when I try to stop the mic I see:

stopping microphone, sending stop action message recordbutton.js:77
Uncaught TypeError: undefined is not a function 

Also there seem to be some missing pics, not a big deal:

ET https://speech-js-sdk-demo.mybluemix.net/images/stop.svg 404 (Not Found) stop.svg:1
GET https://speech-js-sdk-demo.mybluemix.net/images/stop-red.svg 404 (Not Found) stop-red.svg:1
GET https://speech-js-sdk-demo.mybluemix.net/images/stop.svg 404 (Not Found) stop.svg:1
GET https://speech-js-sdk-demo.mybluemix.net/images/stop-red.svg 404 (Not Found) stop-red.svg:1
GET https://speech-js-sdk-demo.mybluemix.net/images/stop.svg 404 (Not Found) stop.svg:1
GET https://speech-js-sdk-demo.mybluemix.net/images/stop-red.svg 404 (Not Found) stop-red.svg:1
GET https://speech-js-sdk-demo.mybluemix.net/images/stop.svg 404 (Not Found) stop.svg:1
GET https://speech-js-sdk-demo.mybluemix.net/images/stop-red.svg 404 (Not Found)

**Comment by nfriedly** [comment]
Try it again now that I'm done re-pushing - same behavior?

**Comment by daniel-bolanos** [comment]
same issue with the mic, it fails to stop it, but maybe my chrome is too old

Version 37.0.2062.120 Ubuntu 12.04 (281580) (64-bit)

Dani

**Comment by nfriedly** [comment]
OK, do you know what line it's coming from? I can just wrap it in a try/catch.

And what about the images - are they still 404'ing for you?

**Comment by daniel-bolanos** [comment]
Initializing views... index.js:29
Initializing session permissions handler sessionpermissions.js:21
Not running, handleMicrophone() recordbutton.js:52
starting mic recordbutton.js:63
Stopping microphone, sending stop action message recordbutton.js:77
Uncaught TypeError: undefined is not a function microphone-stream.js:79
-> one two three four five six seven eight nine and  displaymetadata.js:159

**Comment by nfriedly** [comment]
cool, got it. `stream.getTracks()[0].stop();`

**Comment by nfriedly** [comment]
BTW, I've continued to update the demo and the SDK - I moved the text formatting code over to the SDK today.  I think I'm basically done with changes to the demo - I might try and add one more module to the SDK to read word timings and slow the results down to ensure they don't arrive before the audio could be heard, but it should be only a 1-2 line change to add it to the demo app. This PR could be merged now, or we can wait for that.

Other than that, I believe the SDK is also essentially done for Speech-to-Text, so I'm going to open a ticket there asking for a code review.

I'd also like to add Text-to-Speech support but I believe that will be simpler, assuming that CORS and tokens both work on TTS.

**Comment by nfriedly** [comment]
I added a TimingStream to delay the display of results that are received before the matching audio is played - there's a nice long opus file at https://github.com/watson-developer-cloud/speech-javascript-sdk/raw/master/examples/public/Isac_Newton_spoken_Wikipedia_opus.ogg that you can use to test it.(from https://commons.wikimedia.org/wiki/File:Isaac_Newton.ogg but converted to opus)

The updated code is available at https://speech-js-sdk-demo.mybluemix.net/ right now if you'd like to test it. At this point, I think this is ready to merge.

**Comment by daniel-bolanos** [comment]
Hi @nfriedly , I just tested it, something seems off, look at recognition results from the original demo and from your version (this is sample file number 1):

https://speech-js-sdk-demo.mybluemix.net/

My family absolute is fascinated by the work I'm doing with Watson and I I think they feel a personal sense of pride and satisfaction bout with the fact is not just technology for technology's sake is technology that's actually making a difference and and change in the world. 

https://speech-to-text-demo.mybluemix.net/

My family absolute is fascinated by the work I'm doing with Watson and I I think they feel a personal sense of pride and satisfaction out with the fact is not just technology for technology's sake is technology that's actually making a difference and and changing the world. 

both point to the service in stream so results should be identical.

**Comment by germanattanasio** [comment]
@daniel-bolanos is that something you get everytime you test the app?

**Comment by nfriedly** [comment]
@daniel-bolanos good catch, I missed that. I'll dig into it tomorrow and see what I can figure out.

**Comment by daniel-bolanos** [comment]
@germanattanasio , decoding results for files should be deterministic, same input / same output. @nfriedly thank you!

Dani

**Comment by nfriedly** [comment]
@daniel-bolanos two things of note:

1) today it's actually giving me the same translation:

https://speech-js-sdk-demo.mybluemix.net/

> My family absolute is fascinated by the work I'm doing with Watson and I I think they feel a personal sense of pride and satisfaction out with the fact is not just technology for technology's sake is technology that's actually making a difference and and changing the world. 

https://speech-to-text-demo.mybluemix.net/

> 
My family absolute is fascinated by the work I'm doing with Watson and I I think they feel a personal sense of pride and satisfaction out with the fact is not just technology for technology's sake is technology that's actually making a difference and and changing the world. 

Are you observing that behavior also? Can you think of any reason why it would have change? I have not made any code changes since we both observed the differing results yesterday.

2) I realized why it might be different: I actually changed the underlying behavior of the sample buttons. The current demo app makes an XHR request for the data, then sends one copy to an `<audio>` element as a `Blob` and sends the other copy to the STT service over the Websocket. 

However, in my new version, I just create an `<audio>` element pointed at the source, let the browser handle the download and playback, and then tap into the `<audio>` element to extracting a stream just like we do for microphone input. 

To explain that a little bit: I added support for `<audio>` & `<video>` element sources partially because a different team had requested it and partially because I thought it made a lot of sense for this the JS SDK (and is a relatively small amount of additional code because it can leverage the audio/l16 transformation code we already had in place for mic input). That gives me three main APIs in the JS lib: `recognizeMicrophone()`, `recognizeBlob()`, and `recognizeElement()` - Since they were there and this was a sample app, I thought it would make sense to use all three here.

But I concede that it may have cause an (intermittent?) regression here due to involving the browser's audio processing where it previously wasn't, but I'd still argue that it might be the best plan of attack.

Somewhat related to this, the file I wanted you to review the most in the SDK is https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/webaudio-wav-stream.js - I basically hijacked two sections of you code to output an actual .wav header + convert the WebAudio to l16 - I think I have a halfways decent handle of what's going on, but you did mark the main method as deprecated, so I wanted to know if you had suggestions for what to do there instead. 

(It includes the .wav header mostly for the next stream in the chain, https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-stream.js which then reads the header and automatically sets the content-type, but I was also thinking that the webaudio-wav-stream.js is a good candidate for moving to a standalone library and that it would be more useful with the .wav header.)

**Comment by daniel-bolanos** [comment]
@nfriedly , what I'm observing is that your app is not deterministic for file upload (see below), and that is something that can potentially confuse users. User not only expect to see the same hyp coming from the same file when it is run multiple times, they also expect the demo to produce the same results than the service will produce when calling it directly. This is the way I see it. Is it possible to make some change to your implementation so it becomes deterministic?

-- non deterministic behaviour explained -------------------------

I run your version two times (firefox) and get this:

https://speech-js-sdk-demo.mybluemix.net/

My family **absolutely** fascinated by the work I'm doing with Watson and I I think they feel a personal sense of pride and satisfaction **but** with the fact is not just technology for technology's sake is technology that's actually making a difference and and change in the world. 

My family **absolute is** fascinated by the work I'm doing with Watson and I I think they feel a personal sense of pride and satisfaction **out** with the fact is not just technology for technology's sake is technology that's actually making a difference and and change in the world

Then I run the original demo 4 times (firefox) and got the same output in all runs:

My family absolute is fascinated by the work I'm doing with Watson and I I think they feel a personal sense of pride and satisfaction out with the fact is not just technology for technology's sake is technology that's actually making a difference and and changing the world. 

Then I run it once in Chrome and get the same thing:

My family absolute is fascinated by the work I'm doing with Watson and I I think they feel a personal sense of pride and satisfaction out with the fact is not just technology for technology's sake is technology that's actually making a difference and and changing the world. 

-------------------------------------------------------------------------------

Dani

**Comment by nfriedly** [comment]
So, the sample buttons are *not* file upload in the SDK'd demo app, they are closer to microphone input now (in the sense that we get an audio stream from the browser, convert that to l16, and then upload it.) 

I didn't realize that the output stream from playing an `<audio>` element was non-deterministic, though, so maybe it is worth going back to the old style of downloading the file, then playing + uploading it separately. It's a bit more work, and less ideal in the sense of the demo app showing users how to use the SDK, but it's definitely possible.

**Comment by germanattanasio** [comment]
@nfriedly what about all this work? can we look into this for the new demo?

**Comment by nfriedly** [comment]
At this point, this PR isn't worth the effort it would take to salvage it. However, the issue will be resolved as part of https://github.ibm.com/Watson/developer-experience/issues/453

**Pull request closed without merging**
