### PR TITLE
Add playback support

### PR DESCRIPTION
**Pull request by kasaby**
this change adds playback support for audio you just recorded. This feature is turned off by default, and one line of code needs to be uncommented before it will run. Check the readme for more details.

### CODE REVIEW

**Comment by kasaby** [comment]
@germanattanasio  this time it's against the master :dancer:

**Comment by germanattanasio** [comment]
@kasaby can you also add the updated `index.js`.

Run 
```
npm run build
```

and add `index.js` and commit that file. That will help the users that use the deploy to bluemix.

**Comment by nfriedly** [comment]
@german we should set up a "devops pipeline" to do that automatically on the way to bluemix

**Comment by germanattanasio** [comment]
that's a good idea :p

**Pull request merged**
