### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by daniel-bolanos**
I have added various improvements:

- Improved mechanism to handle punctuation and upper casing
- Hypotheses do no longer come ahead of playback for the provided sample audio files
- Added native (HTML5 Web Audio) support for down sampling
- Inactivity timeout is now 600 seconds instead of the default 30 seconds so it can handle much longer silences without closing the connection

### CODE REVIEW

**Comment by germanattanasio** [comment]
hi @daniel-bolanos, I found a `steam-s` in your code, and your changes will break the "deploy to bluemix" functionality. Please fix that and add a deployed version of the demo with your changes so that we can test them before merge the changes.

**Comment by daniel-bolanos** [comment]
@germanattanasio there are no stream-s in the latest version that I can see, there was one in the README.md but that one was there before. Please try the app here: http://speech-to-text-nodejs-updated.stage1.mybluemix.net/

**Comment by germanattanasio** [comment]
I don't have access to:  http://speech-to-text-nodejs-updated.stage1.mybluemix.net/ :wink: 
but the changes looks good for me

**Comment by daniel-bolanos** [comment]
@germanattanasio the url seems to be working for me, I think the changes are healthy

**Pull request merged**
